### ISSUE TITLE
Migrato linux - linux

### ISSUE THREAD

**Issue by AnonymousWebHacker** [MMMZZZZ/Jellyfin-Migrator#3]
Would this script help me migrate from ubuntu 18.04 to ubuntu 20.04? [without docker]

**Comment by MMMZZZZ** [comment]
I've never done that specific migration but I can't see where you'd need a script like this one. A script like mine is required if you
* change paths (configuration folders, metadata, media, ...)
* Copy/Move/... media files such that their creation or modification date changes. (This does not apply to config or metadata files)

If you're just reinstalling/updating your OS, make sure you got a backup of Jellyfins config and metadata folders, restore them to the same location afterwards and you should be fine. 

Kind regards,
Max

**Comment by AnonymousWebHacker** [comment]
Yes, I did the same, copy of /var/lib/jellyfin , of /etc/jellyfin, replace everything, permissions and that's it
