### ISSUE TITLE
Avoid unnecessary stat calls

### ISSUE THREAD

**Issue by mjpieters** [MMMZZZZ/Jellyfin-Migrator#4]
The following section in the script will _always_ stat existing files:

https://github.com/MMMZZZZ/Jellyfin-Migrator/blob/22595d0b660d7e80a934e89afd6e1453a104717a/jellyfin_migrator.py#L1253-L1266

This is doing a lot of needless, expensive disk reading. I recommend this is only done if `created >= 0 and modified >= 0` is false, because only if at least one of those two values is smaller than 0 do you actually need to have the stat data.

Note that `pathlib.Path()` objects [have a native `stat()` method](https://docs.python.org/3/library/pathlib.html#pathlib.Path.stat), there is no need to use `os.stat()` here (saves an import).

Rearranged to the following the code here can avoid the majority of stat calls and so be _way_ faster:

```python
        created = jf_date_str_to_python_ns(date_created)
        modified = jf_date_str_to_python_ns(date_modified)
        # only call target.stat() if we actually need to update the dates
        if created >= 0 and modified >= 0:
            continue

        filestats = target.stat()
        if created < 0:
            cur.execute(
                "UPDATE `TypedBaseItems` SET `DateCreated` = ? WHERE `rowid` = ?",
                (get_datestr_from_python_time_ns(filestats.st_ctime_ns), rowid),
            )
        if modified < 0:
            cur.execute(
                "UPDATE `TypedBaseItems` SET `DateModified` = ? WHERE `rowid` = ?",
                (get_datestr_from_python_time_ns(filestats.st_mtime_ns), rowid),
            )
```

**Comment by MMMZZZZ** [comment]
Good catch! Thank you for reporting. 

Kind regards,
Max
